[package]
name = "owo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "owo"
path = "src/main.rs"

[lib]
name = "owo"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = { version = "0.7", features = ["macros"] }
sqlx = { version = "0.7", default-features = false, features = [
    "sqlite",
    "macros",
    "runtime-tokio-rustls",
    "migrate",
    "uuid",
    "chrono",
] }
tower-http = { version = "0.5", features = ["trace", "cors", "fs"] }
tower = "0.4"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v7", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

anyhow = "1"
thiserror = "1"

argon2 = "0.5"
password-hash = { version = "0.5", features = ["getrandom"] }
sha2 = "0.10"
hex = "0.4"
zeroize = { version = "1", features = ["derive"] }
rand = "0.8"

base64 = "0.22"

rust_decimal = { version = "1", features = ["serde-with-str"] }

utoipa = { version = "4", features = ["axum_extras", "chrono", "uuid", "decimal"] }
utoipa-swagger-ui = { version = "7", features = ["axum"] }

[dev-dependencies]
reqwest = { version = "0.11", features = ["json"] }
